language: python

dist: bionic

python:
  - "2.7"
  - "3.7"

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy numpy

script:
  # run unit tests
  - cd tests
  - python -m unittest test_surface test_material
