name: Run unittests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --only-binary=numpy numpy
      - name: Run tests
        run: |
          cd tests
          python3 -m unittest discover -s ./
